spring:
  profiles:
    active:
    - production
---
spring:
  config:
    activate:
      on-profile: production

  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:mysql://${DB_HOST}:3306/${DB_NAME}?allowPublicKeyRetrieval=true&useUnicode=yes&characterEncoding=UTF8&verifyServerCertificate=false&useSSL=false&requireSSL=false
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jackson:
    time-zone: "Europe/Helsinki"
    serialization:
      fail-on-empty-beans: false

  servlet:
    multipart:
      enabled: true
      max-file-size: 24MB
      max-request-size: 256MB

  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true

server:
  port: ${PORT:8080}
  
---
spring:
  config:
    activate:
      on-profile: test
    
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
    driver-class-name: org.h2.Driver